Data Exploration Assignment 01
========================================================


```{r loadData}

dir <- { if (file.exists("C:/Temp"))
        "c:/Temp"
        else
          "./"
      }

pF<-'household_power_consumption.txt'


powerDataFile <- {
  cTempFile <- sprintf("%s/%s", "c:/temp", pF)
  locFile <- sprintf("%s/%s", "./", pF)
  if (file.exists(cTempFile))
    cTempFile
  else if (file.exists(pF))
    pF
  else {
    ## stop ("did not locate uncompressed file. Stopped.")
    ## this is machine-dependent
    download.file(
      url='https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip', 
      destfile="c:/temp/housing.zip")
    system("unzip  c:/temp/housing.zip")
    pF 
  }
}

source("chkPkgs.R")
checkPkgs("data.table")

library(data.table)


#### fread currenlty does not accept connections need to pass file name as a 
#### string. that means file has to be unzipped.

f<-fread(powerDataFile, nrows=99)
fClasses<-sapply(f, class)
powerD<-fread(powerDataFile, colClasses=unname(fClasses), na.strings="?", 
              skip=66637, nrow=2880)
setnames(powerD, names(powerD),names(f))
#this is not required since we already filtered rows we needed to read but in case someone passes us full dataset:
setkey(powerD, Date)
powerD<-powerD[J(c("1/2/2007","2/2/2007"))]
#pOrig<-copy(powerD)
# row count of 2880 suggests we set skip and nrow correctly; This save me dev time on re-runs.

### Data munging/transformations
#### adding date field to the data.table
powerD[,DT:=as.POSIXct(
               strptime(
                 sprintf("%s;%s",Date, Time), format="%d/%m/%Y;%H:%M:%S")
               )
       ]
par(mfrow=c(1,1))
```


#Plot 1
```{r plots,fig.width=480,fig.height=480,dependson=loadData}
hist(powerD$Global_active_power,col="red",xlab="Global Active Power (kilowatts)", main="Global Active Power")

```

#Plot 2
```{r gap_date,fig.width=480,fig.height=480,dependson=loadData}

plot(powerD$DT, type="l", powerD$Global_active_power, ylab="Global Active Power (kilowatts)", xlab="", main="")

```

#Plot 3
```{r plot3,fig.width=480,fig.height=480,dependson=loadData}
plot(powerD[,Sub_metering_1]~ powerD$DT, type="n", ylab="Energy sub metering", xlab="", main="", ylim=range(powerD$Sub_metering_1))

with(powerD, lines(Sub_metering_1 ~ DT, col=1))
with(powerD, lines(Sub_metering_2 ~ DT, col=2))
with(powerD, lines(Sub_metering_3 ~ DT, col=4))
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
lty=c(1,1), # set up lines in legend
lwd=c(1,1),col=c(1,2,4)) # set up legend color and width
```
#Plot 4
```{r plot4,fig.width=480,fig.height=480,dependson=loadData}

par(mfrow=c(2,2))

with(powerD, plot(Global_active_power ~ DT, ylab="Global active power", type="l"))

with(powerD, plot(Voltage ~ DT, ylab="Voltage", xlab="datetime", type="l"))

#insert sub_metering
plot(powerD[,Sub_metering_1]~ powerD$DT, type="n", ylab="Energy sub metering", xlab="", main="", ylim=range(powerD$Sub_metering_1))

with(powerD, lines(Sub_metering_1 ~ DT, col=1))
with(powerD, lines(Sub_metering_2 ~ DT, col=2))
with(powerD, lines(Sub_metering_3 ~ DT, col=4))
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),
lty=c(1,1), lwd=c(1,1),col=c(1,2,4)) 
with(powerD, plot(Global_reactive_power ~ DT, xlab="datetime", type="l"))
```
